// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btemgxxiibyvcqhwskgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0ZW1neHhpaWJ5dmNxaHdza2dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MjY4MTAsImV4cCI6MjA2NzAwMjgxMH0.Tl_wN_iLB8rDsAMbrn1FOdsOxmUEeiZp3gi9fgJgpVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});